### ISSUE TITLE
[FIXED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [ErEXON/mp3tag#1]
Dear Rajat,
Could you generate standalone ```.exe``` for the rest of us who are merely users w/o compiler?
Current executable seems to be linked dynamically therefore the following error occurs
```
libgcc_s_seh-1.ddl is missing
```

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by okkosh** [comment]
Hi Aleksandr

It's Fixed Now. Earlier it was compiled in Debugging mode that's why you were facing the linking issues.
Anyway, Thanks for pointing out.

**Comment by sergeevabc** [comment]
Input is [Crepuscular rays over the horizon][1] by Yagya (support [the artist][2] if you like).

Output of ```mp3tag.exe yagya.mp3``` is somehow garbled (compared to [Mediainfo’s one][3]).
```
Album : ��S t a r s   a n d   D u s t
Title : ��C r e p u s c u l a r   R a y s   O v e r   t h e   H o r i z o n
Track : 2
Artist : ��Y A G Y A
Album Artist : ��Y A G Y A
Genre : ��B A S I C   C H A N N E L   /   D U B   T E C H N O
Year : 2016
Publisher :
Composer :
```
And ```mp3tag --play yagya.mp3``` seems not to work.
```
Error : Wrong Arguments and or File.
Remember - Arguments are Case Sensitive. Use IDTE --h For More Information
```

I am scared to use it further, but thanks for letting me try.

[1]: https://transfer.sh/hfZDa/yagya.mp3
[2]: https://yagya.bandcamp.com/
[3]: https://privatebin.net/?c94b9d5b9eb9a79d#itKLsbYzkDK6FwBspFPFDoe5nX40Zf00snh+vl2C3Uc=

**Comment by okkosh** [comment]
Don't worry every file is opened is **read only** mode. 

Also,  you are seeing garbled outputs due to the fact that this program do not support Unicode Characters.

**mp3tag --play** will not work in this case as this is currently a Work in Progress (WIP) feature. If you want to work with a full version of similar software then please try https://sourceforge.net/projects/idte/

Also, Feel free to contribute as this project is no longer maintained and was initiated as a college project.
